apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mario-deployment
  namespace: mario-deployment
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  interval: 1m
  releaseName: ingress-nginx
  chart:
    spec:
      chart: ./nginx/chart
  values:
    controller:
      image:
        repository: rajatrokde/k8-mario:latest
        tag: "v1.1.1"
      replicaCount: 2