apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mariodeployment.fullname" . }}-mario-deployment
  labels:
  {{- include "mariodeployment.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.marioDeployment.replicas }}
  selector:
    matchLabels:
      app: mario
    {{- include "mariodeployment.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: mario
      {{- include "mariodeployment.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.marioDeployment.marioContainer.image.repository }}:{{ .Values.marioDeployment.marioContainer.image.tag
          | default .Chart.AppVersion }}
        name: mario-container
        ports:
        - containerPort: 80
        resources: {}